/**

	@class UserEventUnpacking

	Event-class for the Unpacking step of the analysis.

	RawEvent with raw messages.

*/

#ifndef USEREVENTUNPACKING_H
#define USEREVENTUNPACKING_H

#include <TGo4EventElement.h> // mother class

class TClonesArray;

class UserEventUnpacking : public TGo4EventElement
{
	/*friend class UserProcUnpacking; // provider
	friend class UserProcMonitoring; // consumer*/

public:
	UserEventUnpacking(const char* name = "UserEventUnpacking");
	virtual ~UserEventUnpacking();

	void Clear(Option_t* t = "");

	virtual void Print(Option_t* option = "") const;

public: //TODO should be private. Made public for ER

	/**
	 * One message is, in essence, a pair (ch,val).
	 * This data is accompanied by lots of other
	 * values from the event header, subevent header,
	 * subsbevent header and footer, etc.
	 * See data/RawMessage.h
	 */
	TClonesArray* fRawMessages;

	/**
	 * Data from CAMAC as if generated by the MWPCs.
	 * H - header, F - footer, X - used half-byte.
	 * last 2 bytes are extracted from the raw data into fCAMAC
	 * HHHHHHHH
	 * 0000XXXX - fCAMAC[0]
	 * 0000XXXX - fCAMAC[1]
	 * FFFFFFFF
	 * HHHHHHHH
	 * 0000XXXX - fCAMAC[2]
	 * 0000XXXX - fCAMAC[3]
	 * FFFFFFFF
	 * HHHHHHHH
	 * 0000XXXX - fCAMAC[4]
	 * 0000XXXX - fCAMAC[5]
	 * FFFFFFFF
	 * HHHHHHHH
	 * 0000XXXX - fCAMAC[6]
	 * 0000XXXX - fCAMAC[7]
	 * FFFFFFFF
	 */
	Short_t fCAMAC[8];

	/**
	 * This data field duplicates the trigger which is written with each raw message
	 */
	Short_t fTrigger;

	ClassDef(UserEventUnpacking, 1);
};

#endif // USEREVENTUNPACKING_H
